namespace FrontCameraAssembleEquipment.Defines
{
    public enum ECameraFlipperInput
    {
        CAM_OUT_DONE,
        CAMHEAD_VAC_ON_OK,
        CAM_ASSEMBLE_HEAD_READY_DONE,

        PREALIGN_CAMERA_DETECTED,
        PREALIGN_CENTERING_OPEN_DONE,
        PREALIGN_ROTATOR_LOAD_REQUEST,
        PREALIGN_ROTATOR_REMOVE_SPONGE_REQUEST,
        PREALIGN_ROTATOR_UNLOAD_REQUEST,
        PREALIGN_READY_DONE,

        TAPE_READY_DONE,
    }
}
